/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.tche.ucpel.trabalhomertins.view;

import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author Natanael
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private FormAluno formAluno;
    private FormProfessor formProfessor;
    private FormDisciplinas formDisciplinas;
    private FormCurso formCurso;
    private FormMatricula formMatricula;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCAlunos = new javax.swing.JMenuItem();
        jMenuCProfessores = new javax.swing.JMenuItem();
        jMenuCCurso = new javax.swing.JMenuItem();
        jMenuCDisciplinas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuRMatricula = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(TelaPrincipal.class.getResource("/br/tche/ucpel/imagens/ucpel.png")).getImage());

        jMenu1.setText("Cadastro");

        jMenuCAlunos.setText("Cadastro de Alunos");
        jMenuCAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCAlunosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCAlunos);

        jMenuCProfessores.setText("Cadastro de Professores");
        jMenuCProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCProfessoresActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCProfessores);

        jMenuCCurso.setText("Cadastro de Curso");
        jMenuCCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCCursoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCCurso);

        jMenuCDisciplinas.setText("Cadastro de Disciplinas");
        jMenuCDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCDisciplinasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCDisciplinas);
        jMenu1.add(jSeparator2);

        jMenuRMatricula.setText("Realização da Matricula");
        jMenuRMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRMatriculaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuRMatricula);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Professor");

        jMenuItem6.setText("Notas dos alunos");
        jMenu3.add(jMenuItem6);

        jMenuItem8.setText("Atualização de Presença");
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Aluno");

        jMenuItem9.setText("Historico");
        jMenu4.add(jMenuItem9);

        jMenuItem11.setText("Professores");
        jMenu4.add(jMenuItem11);

        jMenuItem12.setText("Horario");
        jMenu4.add(jMenuItem12);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Ajuda");

        jMenuItem5.setText("Sobre");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Sair");

        jMenuItem10.setText("Sair");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 881, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(889, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JOptionPane.showMessageDialog(this, "Sistema de controle Acadêmico \nCiência da Computação/UCPel\n\nAlunos:\n"
                + " Matheus Dobke \n" + " Natanael Signorini", "Trabalho 1", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuCAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCAlunosActionPerformed
        if (this.formAluno == null) {
            this.formAluno = new FormAluno(this);
            //this.desktopPane.add(this.formAluno);
        }
        this.openJanela(this.formAluno);

    }//GEN-LAST:event_jMenuCAlunosActionPerformed

    private void jMenuCProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCProfessoresActionPerformed
        if (this.formProfessor == null) {
            this.formProfessor = new FormProfessor(this);
            this.desktopPane.add(this.formProfessor);
        }
        this.openJanela(this.formProfessor);
    }//GEN-LAST:event_jMenuCProfessoresActionPerformed

    private void jMenuCDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCDisciplinasActionPerformed
       if (this.formDisciplinas == null) {
            this.formDisciplinas = new FormDisciplinas(this);
            this.desktopPane.add(this.formDisciplinas);
        }
        this.openJanela(this.formDisciplinas);
    }//GEN-LAST:event_jMenuCDisciplinasActionPerformed

    private void jMenuCCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCCursoActionPerformed
         if (this.formCurso == null) {
            this.formCurso = new FormCurso(this);
            this.desktopPane.add(this.formCurso);
        }
        this.openJanela(this.formCurso);
    }//GEN-LAST:event_jMenuCCursoActionPerformed

    private void jMenuRMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRMatriculaActionPerformed
        if (this.formMatricula == null) {
            this.formMatricula = new FormMatricula(this);
            this.desktopPane.add(this.formMatricula);
        }
        this.openJanela(this.formMatricula);
                                      
    }//GEN-LAST:event_jMenuRMatriculaActionPerformed
    private void openJanela(JComponent obj) {
        if (!obj.isVisible()) {
            if (!obj.isValid()) {
                desktopPane.add(obj);
            }

            obj.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCAlunos;
    private javax.swing.JMenuItem jMenuCCurso;
    private javax.swing.JMenuItem jMenuCDisciplinas;
    private javax.swing.JMenuItem jMenuCProfessores;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuRMatricula;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
